import sys
import os
import logging

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.research.research_report import generate_markdown_report

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ReportGenerator")

def main():
    logger.info("Generating standalone research report from latest analysis results...")
    # This would typically read from a JSON file generated by run_research.py
    logger.info("Done.")

if __name__ == "__main__":
    main()
