import os
import sys
import pandas as pd
import numpy as np
import logging
from pathlib import Path
from datetime import datetime

# Configure logging for Android Logcat
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("BCBIST_Mobile")

# Import our production core
try:
    from app.ml.production_manager import ProductionManager
    from app.config import BASE_DIR, BREADTH_DATA_PATH, STOCK_UNIVERSE
    from app.data.market_data import MarketDataProvider
    from app.features.feature_pipeline import run_feature_pipeline
except ImportError:
    # If running from inside Android Python path
    from ml.production_manager import ProductionManager
    from config import BASE_DIR, BREADTH_DATA_PATH, STOCK_UNIVERSE
    from data.market_data import MarketDataProvider
    from features.feature_pipeline import run_feature_pipeline

class MobileDecisionEngine:
    def __init__(self, data_dir: str):
        """
        data_dir: The persistent files directory provided by Android.
        """
        self.data_dir = Path(data_dir)
        # Point config to use mobile paths if needed
        os.environ['MODELS_DIR'] = str(Path(__file__).parent / "models")

        config_path = Path(__file__).parent / "configs" / "production" / "production_config.json"
        self.pm = ProductionManager(config_path)
        self.market_provider = MarketDataProvider()

    def run_daily_analysis(self, symbols_limit=100) -> str:
        """
        Main execution loop for on-device analysis.
        Uses full 5-year feature set + Active News.
        """
        logger.info(f"Starting High-Accuracy analysis for Top {symbols_limit} symbols...")

        # 1. Fetch Data (yfinance) - Ensure we get latest active data
        symbols = [s['symbol'] for s in STOCK_UNIVERSE[:symbols_limit]]

        # Use full window for Darvas and Technical consistency
        end_date = datetime.now().strftime("%Y-%m-%d")
        start_date = (datetime.now() - pd.Timedelta(days=180)).strftime("%Y-%m-%d")

        all_raw = {}
        for sym in symbols:
            df = self.market_provider.fetch_ohlcv(sym, start_date, end_date)
            if not df.empty:
                all_raw[sym] = df

        if not all_raw:
            return "ERROR: Active data fetch failed"

        # 2. Feature Building - INCLUDING EVENTS/NEWS
        logger.info("Building full feature set (Technical + Sector + News)...")
        processed_data = run_feature_pipeline(all_raw, include_events=True)

        # Aligment
        latest_date = max([df.index.max() for df in processed_data.values()])

        all_rows = []
        for sym, df in processed_data.items():
            if latest_date in df.index:
                row = df.loc[[latest_date]].copy()
                row['symbol_col'] = sym
                all_rows.append(row)

        day_data = pd.concat(all_rows)

        # 3. Market Context (Static fallback if web fails)
        if Path(BREADTH_DATA_PATH).exists():
             mkt_df = pd.read_csv(BREADTH_DATA_PATH, index_col='date', parse_dates=True)
             mkt_data = mkt_df[mkt_df.index <= latest_date].tail(20)
        else:
             # Create a neutral market row if data is missing
             mkt_data = pd.DataFrame([{"regime": "NORMAL", "market_quality": 50.0}], index=[latest_date])

        # 4. Generate Picks & PDF
        logger.info("Running ML inference...")
        response = self.pm.get_daily_picks(day_data, mkt_data)

        # 5. Return PDF Path
        pdf_path = Path(self.data_dir) / f"BCBIST_REPORT_{latest_date.strftime('%Y-%m-%d')}.pdf"
        # The PDF is already generated by ProductionManager inside DATA_REPORTS_DIR/daily
        # Copying it to the accessible Android path
        actual_pdf = Path(os.environ.get('DATA_REPORTS_DIR', 'data/reports')) / "daily" / f"BCBIST_REPORT_{latest_date.strftime('%Y-%m-%d')}.pdf"

        return str(actual_pdf)

def start_analysis(data_path: str):
    """Entry point for Kotlin"""
    engine = MobileDecisionEngine(data_path)
    return engine.run_daily_analysis()
