import pandas as pd
import json
from pathlib import Path
from datetime import datetime

class DailyReportGenerator:
    """
    Generates production reports for the BCBIST decision engine.
    """
    def __init__(self, report_dir: Path):
        self.report_dir = report_dir
        self.report_dir.mkdir(parents=True, exist_ok=True)

    def generate_daily_report(self, prediction_response: dict):
        date_str = prediction_response['date'][:10]
        base_name = f"DAILY_TOPK_{date_str}"

        # 1. JSON Report
        with open(self.report_dir / f"{base_name}.json", 'w') as f:
            json.dump(prediction_response, f, indent=4)

        # 2. Markdown Report
        md_content = self._to_markdown(prediction_response)
        with open(self.report_dir / f"{base_name}.md", 'w') as f:
            f.write(md_content)

        return self.report_dir / f"{base_name}.md"

    def _to_markdown(self, data: dict) -> str:
        md = f"# BCBIST Production Report: {data['date'][:10]}\n\n"
        md += f"## Market Context\n"
        md += f"- **Regime**: {data['market_regime']}\n"
        md += f"- **Quality Score**: {data['market_quality']:.2f}/100\n"
        md += f"- **Drift Score**: {data['drift_score']:.4f}\n"
        md += f"- **Selected K**: {data['selected_k']}\n\n"

        if data['status'] == 'ABSTAIN':
            md += f"> [!CAUTION]\n> SYSTEM ABSTAINED: {data['reason']}\n"
        else:
            md += f"## Top Selections\n"
            md += "| Rank | Symbol | Sector | Probability | Reason |\n"
            md += "| :--- | :--- | :--- | :--- | :--- |\n"
            for p in data['predictions']:
                md += f"| {p['rank']} | **{p['symbol']}** | {p['sector']} | {p['probability']:.2%} | {p['reason']} |\n"

        md += f"\n\n--- \n*Generated by BCBIST ML Engine Phase 22 Champion*"
        return md
